### ISSUE TITLE
Repeat value

### ISSUE THREAD

**Issue by picsoung** [risul/meteor-bootstrap-x-editable#1]
Hi,
Just discovered your package, thanks for the hard work :)

I want to use it to let users be able to edit some fields of their profile easily.

when I load the page it works fine, I have the current value loaded in the field.

![botz_io](https://cloud.githubusercontent.com/assets/172072/7713321/5416aaac-fe77-11e4-8bde-0028c7dc8cbc.png)

I can edit fine. I can retrieve the value from the `success` event and then call a method to update the value.
But then when I updated the value in the DB, it displays the new value twice.

![botz_io](https://cloud.githubusercontent.com/assets/172072/7713350/83d5f716-fe77-11e4-8e75-d075832377b1.png)

my view code

``` html
<a href="#" id="emailField" data-type="text" data-pk="{{_id}}" data-title="Enter email" class="editable editable-click" style="display: inline;">
            {{profile.email}}
        </a>
```

``` js
emplate.dashboardAccount.rendered = function(){
    $('#emailField.editable').editable({
        mode: 'inline',
        success: function(response, newValue) {
            var userId = $("#emailField").data('pk');
            Meteor.call('updateUserEmail',userId,newValue);
        }
    });
}
```

thanks for your help :)

**Comment by risul** [comment]
Sorry for late response... somehow all mails from github is going to my spam folder.
Reactive update can be tricky with most of the form related libraries and there are multiple work arounds available.

Please refer to this SO answer: http://stackoverflow.com/a/23144211
